server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args: USER-SERVICE
              fallbackuri: forward:/userServiceFallBack
        -id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**.
          filters:
            - name: CircuitBreaker
              args: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentServiceFallBack

#this hystrix will send divert if no response in 4s
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#            send information to the hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

